name: Build iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
    - name: Build
      run: |
          ionic cordova platform add ios
          ionic cordova prepare ios
          cd platforms/ios
          ls -R
          #xcodebuild clean test -project "Ionic Conference App.xcodeproj" -scheme "Ionic Conference App" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
          xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project "Ionic Conference App.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/ios/build/emulator/Ionic\ Conference\ App.app
        
